services:
  #############################################################################
  # uno (default) images
  #############################################################################
  uno:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno:dev
      platforms:
      - linux/amd64
      args:
        BASE_IMAGE: ubuntu:22.04
  test-runner:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno-test-runner:latest
      platforms:
      - linux/amd64
      args:
        DEV: y
        BASE_IMAGE: ubuntu:22.04
  uno-arm64:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno:dev-arm64
      platforms:
        - linux/arm64
      args:
        BASE_IMAGE: ubuntu:22.04
  test-runner-arm64:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno-test-runner:latest-arm64
      platforms:
        - linux/arm64
      args:
        DEV: y
        BASE_IMAGE: ubuntu:22.04
  #############################################################################
  # uno (default) edge images
  #############################################################################
  uno-edge:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno:dev
      args:
        BASE_IMAGE: ubuntu:24.04
  #############################################################################
  # Debian package builders
  #############################################################################
  debian-builder:
    build:
      context: .
      dockerfile: docker/debian-builder/Dockerfile
      tags:
        - mentalsmash/debian-builder:latest
      platforms:
        - linux/amd64
      args:
        BASE_IMAGE: ubuntu:22.04
  debian-builder-arm64:
    build:
      context: .
      dockerfile: docker/debian-builder/Dockerfile
      tags:
        - mentalsmash/debian-builder:latest-arm64
      platforms:
        - linux/arm64
      args:
        BASE_IMAGE: ubuntu:22.04
  #############################################################################
  # Debian package testers
  #############################################################################
  debian-tester:
    build:
      context: .
      dockerfile: docker/debian-tester/Dockerfile
      tags:
        - mentalsmash/debian-tester:latest
      platforms:
        - linux/amd64
      args:
        BASE_IMAGE: ubuntu:22.04
  debian-tester-arm64:
    build:
      context: .
      dockerfile: docker/debian-tester/Dockerfile
      tags:
        - mentalsmash/debian-tester:latest-arm64
      platforms:
        - linux/arm64
      args:
        BASE_IMAGE: ubuntu:22.04

