services:
  #############################################################################
  # uno (default) images
  #############################################################################
  uno:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno:dev
      args:
        UNO_MIDDLEWARE: uno_middleware_connext
        BASE_IMAGE: ubuntu:22.04
  test-runner:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno-test-runner:latest
      args:
        DEV: y
        UNO_MIDDLEWARE: uno_middleware_connext
        BASE_IMAGE: ubuntu:22.04
  uno-arm64:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno:dev-arm64
      platforms:
        - linux/arm64
      args:
        UNO_MIDDLEWARE: uno_middleware_connext
        BASE_IMAGE: ubuntu:22.04
  test-runner-arm64:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno-test-runner:latest-arm64
      args:
        DEV: y
        UNO_MIDDLEWARE: uno_middleware_connext
        BASE_IMAGE: ubuntu:22.04
  #############################################################################
  # uno (default) edge images
  #############################################################################
  uno-edge:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno:dev
      args:
        UNO_MIDDLEWARE: uno_middleware_connext
        BASE_IMAGE: ubuntu:24.04
  #############################################################################
  # uno (static) images
  #############################################################################
  uno-static:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno:dev-static
      args:
        UNO_MIDDLEWARE: uno.middleware.connext
        BASE_IMAGE: ubuntu:22.04
  test-runner-static:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno-test-runner:latest
      args:
        DEV: y
        UNO_MIDDLEWARE: uno.middleware.native
        BASE_IMAGE: ubuntu:22.04
  #############################################################################
  # uno (static) edge images
  #############################################################################
  uno-static-edge:
    build:
      context: .
      dockerfile: docker/Dockerfile
      tags:
        - mentalsmash/uno:dev
      args:
        UNO_MIDDLEWARE: uno.middleware.native
        BASE_IMAGE: ubuntu:24.04
