#!/usr/bin/env python3
import argparse
import subprocess
import json

parser = argparse.ArgumentParser()

parser.add_argument("-t", "--tag",
  help="Source image tag.",
  required=True)

parser.add_argument("-m", "--metadata",
  help="A JSON object containing image metadata, generated by docker/metadata-action.",
  required=True)

args = parser.parse_args()

source_tag = args.tag
metadata = json.loads(args.metadata)

annotations = [
  tkn
  for annotation in metadata["annotations"]
    for tkn in ["--annotation", annotation]
]

for generated_tag in metadata["tags"]:
  subprocess.run([
    "docker", "buildx", "imagetools", "create",
      "-t", generated_tag,
      *(tkn
        for annotation in metadata["annotations"]
          for tkn in ["--annotation", annotation]),
      source_tag,
  ])

