name: Install Test Image
run-name: |
  install test (${{inputs.install-rti-license && 'default' || 'static'}}) - ${{inputs.tag}} on ${{inputs.platform}} [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}]

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      platform:
        type: string
        required: true
      install-rti-license:
        type: boolean
        default: true

jobs:
  test-config:
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ steps.config.outputs.RUNNER }}
      TEST_ARTIFACT: ${{ steps.config.outputs.TEST_ARTIFACT }}
      TEST_ID: ${{ steps.config.outputs.TEST_ID }}
    steps:
      - name: "Generate test config"
        id: config
        run: |
          case "${{inputs.install-rti-license}}" in
            false)
              suffix=-static
              ;;
            *)
              suffix=
              ;;
          esac
          image_tag=$(echo ${{inputs.tag}}  | tr : - | tr / -)
          test_id=$(date +%Y%m%d-%H%M%S)${suffix}
          test_artifact=${image_tag}-install-test-${{ inputs.platform }}__${test_id}
          (
            case "${{ inputs.platform }}" in
              arm64)
                case "${{inputs.install-rti-license}}" in
                  true)
                    # Force full test suite to run on "beefier" rpi5 nodes
                    printf -- "RUNNER='%s'\n" '["self-hosted", "linux", "arm64", "rpi5"]'
                    ;;
                  *)
                    # Other test suites can run on any arm64 node
                    printf -- "RUNNER='%s'\n" '["self-hosted", "linux", "arm64"]'
                    ;;
                esac
                ;;
              amd64)
                printf -- "RUNNER='%s'\n" '"ubuntu-latest"'
                ;;
            esac
            echo TEST_ARTIFACT=${test_artifact}
            echo TEST_ID=${test_id}
          ) >> ${GITHUB_OUTPUT}

  test-spec-docker:
    needs: test-config
    runs-on: ubuntu-latest
    steps:
      - name: Clone uno
        uses: actions/checkout@v4
        with:
          path: src/uno
          submodules: true
    
      - name: Clone build support files
        uses: actions/checkout@v4
        with:
          repository: mentalsmash/uno-ci
          token: ${{ secrets.UNO_CI_PAT }}
          ref: master
          path: src/uno-ci

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: inputs.platform != 'amd64'

      - name: "Set up test environment"
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip3 install pytest

      - name: "Run install tests"
        if: inputs.install-rti-license
        run: |
          . venv/bin/activate
          RTI_LICENSE_FILE=src/uno-ci/resource/rti/rti_license.dat \
          UNO_IMAGE=${{inputs.tag}} \
          PLATFORM=${{inputs.platform}} \
          FORCE_PULL=yes \
          pytest -s -v --junit-xml=test-results/uno-test-results-install-${{ needs.test-config.outputs.TEST_ID }}.xml \
            src/uno/test/install
    
      - name: "Run install tests (without a license)"
        if: ${{ !inputs.install-rti-license }}
        run: |
          . venv/bin/activate
          RTI_LICENSE_FILE= \
          UNO_IMAGE=${{inputs.tag}} \
          PLATFORM=${{inputs.platform}} \
          FORCE_PULL=yes \
          pytest -s -v --junit-xml=test-results/uno-test-results-install-${{ needs.test-config.outputs.TEST_ID }}.xml \
            src/uno/test/install

      - name: Restore permissions changed by tests
        if: always()
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            ${{inputs.tag}} \
            fix-file-ownership $(id -u):$(id -g) /workspace

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ needs.test-config.outputs.TEST_ARTIFACT }}
          path: test-results/*
