name: pr-premerge

on:
  pull_request_review:
    types: [submitted]


concurrency:
  # Don't run workflow in parallel for the same PR
  group: ${{ github.workflow }}${{ github.ref }}


jobs:
  build_and_test:
    if: github.event.review.state == 'APPROVED'
    strategy:
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04"]
        uno-middleware: [uno.middleware.native] #, uno_middleware_connext]
        exclude:
          - base-image: ubuntu:24.04
            uno-middleware: uno_middleware_connext
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    with:
      base-image: ${{ matrix.base-image }}
      uno-middleware: ${{ matrix.uno-middleware }}

