name: PR Full Test (begin check run)

on:
  workflow_run:
    workflows: [PR Full Test]
    types: [in_progress]

jobs:
  start_check_run:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PR Full Test
          status: 'in_progress'
