name: pr-premerge

on:
  pull_request:
    branches:
      - master
    paths:
      - 'pyproject.toml'
      - 'uno/**/*'
      - 'test/**/*'
      - 'docker/**/*'
      - '.github/**/*'

  pull_request_review:
    types: [submitted]


concurrency:
  # Don't run workflow in parallel for the same PR
  group: ${{ github.workflow }}${{ github.ref }}


jobs:
  check_approval:
    runs-on: ubuntu-latest
    steps:
      - name: "Fail if review hasn't been approved"
        run: exit 1
        if: github.event.review.state == 'APPROVED'

  build_and_test:
    needs: check_approval
    strategy:
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04"]
        uno-middleware: [uno.middleware.native] #, uno_middleware_connext]
        exclude:
          - base-image: ubuntu:24.04
            uno-middleware: uno_middleware_connext
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    with:
      base-image: ${{ matrix.base-image }}
      uno-middleware: ${{ matrix.uno-middleware }}

