name: CI
run-name: |
  CI test (${{inputs.uno-middleware||'default'}}, ${{inputs.base-image}}, ${{inputs.build-platform}}) ${{inputs.run-unit && '[U]' || ''}}${{inputs.run-unit && '[I]' || ''}}[${{github.ref_name}}${{github.ref_type == 'branch' && '@' || ''}}${{github.ref_type == 'branch' && github.sha || ''}}]

on:
  workflow_call:
    inputs:
      uno-middleware:
        type: string
      base-image:
        type: string
        required: true
      build-platform:
        type: string
        required: true
      run-unit:
        type: boolean
        default: true
      run-integration:
        type: boolean
        default: true
      test-without-license:
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      uno-middleware:
        description: "uno middleware plugin"
        type: string
      base-image:
        description: "base OS image"
        type: string
        required: true
      build-platform:
        description: "linux build platform"
        type: string
        required: true
      run-unit:
        description: "run unit tests"
        type: boolean
        default: true
      run-integration:
        description: "run integration tests"
        type: boolean
        default: true
      test-without-license:
        description: "test also without an RTI license"
        type: boolean
        default: true

concurrency:
  group: ci-build-${{ github.ref }}-${{ inputs.uno-middleware || 'default' }}-${{ inputs.build-platform }}-${{ inputs.base-image }}-${{inputs.test-without-license}}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ fromJson(steps.config.outputs.RUNNER) }}
      TEST_ARTIFACT: ${{ steps.config.outputs.TEST_ARTIFACT }}
      TEST_IMAGE: ${{ steps.config.outputs.TEST_IMAGE }}
      TEST_BASE_IMAGE: ${{ steps.config.outputs.TEST_BASE_IMAGE }}
      TEST_DATE: ${{ steps.config.outputs.TEST_DATE }}
      TEST_ID: ${{ steps.config.outputs.TEST_ID }}
    steps:
      - name: Clone uno
        uses: actions/checkout@v4
        with:
          path: src/uno
          submodules: true

      - name: Generate build and test configuration
        id: config
        run: |
          case "${{github.ref_type}}" in
            tag)
              image_version=${{github.ref_name}}
              ;;
            *)
              sha_short=$(cd src/uno && git rev-parse --short HEAD)
              image_version=${{github.ref_name}}@${sha_short}
              ;;
          esac
          image_version="$(echo ${image_version} | tr / -)"
          middleware_id=$(echo ${{inputs.uno-middleware}} | sed -e 's/uno.middleware.//')
          base_image_tag=$(echo "${{ inputs.base-image }}" | tr : -)
          test_base_image=ghcr.io/mentalsmash/uno-ci-base-tester:${base_image_tag}
          test_image=${{ github.repository }}-test-runner:latest
          test_date=$(date +%Y%m%d-%H%M%S)
          test_id=ci-${middleware_id:-default}-${{ inputs.build-platform }}__${image_version}
          test_artifact=uno-test-${test_id}__${test_date}
          (
            case "${{ inputs.build-platform }}" in
              arm64)
                case "${{inputs.test-without-license}}" in
                  false)
                    # Force full test suite to run on "beefier" rpi5 nodes
                    printf -- "RUNNER='%s'\n" '["self-hosted", "linux", "arm64", "rpi5"]'
                    ;;
                  true)
                    # Other test suites can run on any arm64 node
                    printf -- "RUNNER='%s'\n" '["self-hosted", "linux", "arm64"]'
                    ;;
                esac
                ;;
              amd64)
                printf -- "RUNNER='%s'\n" '"ubuntu-latest"'
                ;;
            esac
            echo TEST_IMAGE=${test_image}
            echo TEST_ARTIFACT=${test_artifact}
            echo TEST_ID=${test_id}
            echo TEST_DATE=${test_date}
            echo TEST_BASE_IMAGE=${test_base_image}
            echo REG_TAG=${ref_tag}
          ) >> ${GITHUB_OUTPUT}

  build-n-test:
    needs: config
    runs-on: ${{ fromJson(needs.config.outputs.RUNNER) }}
    steps:
      - name: Clone uno
        uses: actions/checkout@v4
        with:
          path: src/uno
          submodules: true

      - name: Validate code
        run: |
          . src/uno/.venv/bin/activate
          ruff check

      - name: Validate code format
        run: |
          . src/uno/.venv/bin/activate
          ruff format --check

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Log in to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tester image
        uses: docker/build-push-action@v5
        with:
          file: src/uno/docker/Dockerfile
          tags: ${{ needs.config.outputs.TEST_IMAGE }}
          load: true
          context: src/uno
          platforms: linux/${{ inputs.build-platform }}
          build-args: |
            TEST=y
            BASE_IMAGE=${{ needs.config.outputs.TEST_BASE_IMAGE }}
            UNO_MIDDLEWARE=${{ inputs.uno-middleware }}

      - name: Set up integration tests
        if: ${{ inputs.run-integration }}
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            ${{ needs.config.outputs.TEST_IMAGE }} \
            cp /rti_license.dat /workspace/rti_license.dat

      - name: Run unit tests
        if: inputs.run-unit
        run: |
          make -C src/uno test-unit
        env:
          DEBUG: ${{ runner.debug }}
          IN_DOCKER: y
          RTI_LICENSE_FILE: ${{ github.workspace }}/rti_license.dat
          TEST_DATE: ${{ needs.config.outputs.TEST_DATE }}
          TEST_ID: ${{ needs.config.outputs.TEST_ID }}
          TEST_IMAGE: ${{ needs.config.outputs.TEST_IMAGE }}
          VERBOSITY: ${{ runner.debug && 'debug' || '' }}
          UNO_MIDDLEWARE: ${{ inputs.uno-middleware }}

      - name: Run unit tests (without license)
        if: inputs.run-unit && inputs.test-without-license
        run: |
          make -C src/uno test-unit
        env:
          DEBUG: ${{ runner.debug }}
          IN_DOCKER: y
          NO_LICENSE: y
          TEST_DATE: ${{ needs.config.outputs.TEST_DATE }}
          TEST_ID: ${{ needs.config.outputs.TEST_ID }}
          TEST_IMAGE: ${{ needs.config.outputs.TEST_IMAGE }}
          VERBOSITY: ${{ runner.debug && 'debug' || '' }}
          UNO_MIDDLEWARE: ${{ inputs.uno-middleware }}

      - name: Run integration tests
        if: inputs.run-integration && !inputs.test-without-license
        run: |
          make -C src/uno test-integration
        env:
          DEBUG: ${{ runner.debug }}
          IN_DOCKER: y
          RTI_LICENSE_FILE: ${{ github.workspace }}/rti_license.dat
          TEST_DATE: ${{ needs.config.outputs.TEST_DATE }}
          TEST_ID: ${{ needs.config.outputs.TEST_ID }}
          TEST_IMAGE: ${{ needs.config.outputs.TEST_IMAGE }}
          VERBOSITY: ${{ runner.debug && 'debug' || '' }}
          UNO_MIDDLEWARE: ${{ inputs.uno-middleware }}
      
      - name: Run integration tests (without license)
        if: inputs.run-integration && inputs.test-without-license
        run: |
          make -C src/uno test-integration
        env:
          DEBUG: ${{ runner.debug }}
          IN_DOCKER: y
          NO_LICENSE: y
          TEST_DATE: ${{ needs.config.outputs.TEST_DATE }}
          TEST_ID: ${{ needs.config.outputs.TEST_ID }}
          TEST_IMAGE: ${{ needs.config.outputs.TEST_IMAGE }}
          VERBOSITY: ${{ runner.debug && 'debug' || '' }}
          UNO_MIDDLEWARE: ${{ inputs.uno-middleware }}

      - name: Restore permissions changed by integration tests
        if: always()
        run: |
          make -C src/uno fix-root-permissions
        env:
          FIX_DIR: ${{ github.workspace }}
          TEST_IMAGE: ${{ needs.config.outputs.TEST_IMAGE }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ needs.config.outputs.TEST_ARTIFACT }}
          path: src/uno/test-results/*

