name: CI (Full)
run-name: |
  Full CI test ${{inputs.run-unit && '[U]' || ''}}${{inputs.run-unit && '[I]' || ''}}[${{github.ref_name}}${{github.ref_type == 'branch' && '@' || ''}}${{github.ref_type == 'branch' && github.sha || ''}}]

on:
  workflow_dispatch:
    inputs:
      run-unit:
        type: boolean
        default: true
      run-integration:
        type: boolean
        default: true


concurrency:
  group: ci-build-full-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-n-test:
    strategy:
      matrix:
        build-platform: [amd64, arm64]
        base-image: [ubuntu:22.04]
        uno-middleware: [uno_middleware_connext, uno.middleware.native]
        run-unit: ${{inputs.run-unit && fromJson('[true]') || fromJson('[false]')}}
        run-integration: ${{inputs.run-integration && fromJson('[true]') || fromJson('[false]')}}
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      build-platform: ${{matrix.build-platform}}
      base-image: ${{matrix.base-image}}
      uno-middleware: ${{matrix.uno-middleware}}

