name: Build and push images (release)

on:
  workflow_call:

concurrency:
  group: ci-release-images
  cancel-in-progress: true

jobs:
  push_images:
    uses: ./.github/workflows/push_images.yml
    secrets: inherit
    with:
      tag-default: latest
      tag-static:  latest-static
      base-image-default: ubuntu:22.04
      base-image-static:  ubuntu:24.04
      middleware-default: uno_middleware_connext
      middleware-static:  uno.middleware.native

  update_badges:
    needs: push_images
    uses: ./.github/workflows/update_image_badges.yml
    secrets: inherit
    with:
      tag-default: latest
      tag-static:  latest-static
      base-image-default: ubuntu:22.04
      base-image-static:  ubuntu:24.04
      badge-default-version: "29b57b0427def87cc3ef4ab81c956c29"
      badge-default-base:    "2d53344e1ccfae961665e08432f18113"
      badge-static-version:  "d73e338805c7d2c348a2d7149a66f66c"
      badge-static-base:     "373e55438055b1222c9937797c949f9b"

  update_release_badge:
    runs-on: ubuntu-latest
    needs: push_images
    steps:
    - uses: actions/checkout@v4

    - name: Generate derived variables
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Update latest-release badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE_TOKEN }}
        gistID: "fb644ccb3cbb57b2636f9eca808b9931"
        filename: uno-badge-latest-release.json
        label: latest release
        message: ${{ github.ref_name }}${{ github.ref_type == 'branch' && '@' || '' }}${{ github.ref_type == 'branch' && steps.vars.outputs.sha_short || '' }}
        color: ${{ github.ref_type == 'tag' && 'green' || 'orange' }}

