name: Build and push images (nightly)

on:
  workflow_call:
  
  workflow_dispatch:

concurrency:
  group: ci-nightly-images
  cancel-in-progress: true


jobs:
  push_images:
    uses: ./.github/workflows/push_images.yml
    secrets: inherit
    with:
      tag-default: nightly
      tag-static:  nightly-static
      base-image-default: ubuntu:22.04
      base-image-static:  ubuntu:24.04
      middleware-default: uno_middleware_connext
      middleware-static:  uno.middleware.native

  
  update_badges:
    needs: push_images
    uses: ./.github/workflows/update_image_badges.yml
    secrets: inherit
    with:
      tag-default: nightly
      tag-static:  nightly-static
      base-image-default: ubuntu:22.04
      base-image-static:  ubuntu:24.04
      badge-default-version: "e7aab205f782cc0c6f394a2fece90509"
      badge-default-base:    "8f31c46dcfd0543b42f356e5b1c6c2c8"
      badge-static-version:  "b310f08c34f051846877aeb59b0be311"
      badge-static-base:     "b0e38a84eb8679d5212e162fbb616773"

