name: Build and push images
run-name: "${{ inputs.repo }}:(${{ inputs.tag-default}}, ${{ inputs.tag-static }}) = ${{ github.ref_type }} ${{ github.ref_name }}${{ github.ref_type == 'branch' && ' @ ' || '' }}${{ github.ref_type == 'branch' && github.sha || '' }}"

concurrency:
  group: ${{ github.workflow }} for ${{ github.ref_type }} ${{ github.ref_name }} generates ${{ inputs.repo }}:${{ inputs.tag-default}}, and ${{ inputs.repo }}:${{ inputs.tag-static }}

on:
  workflow_call:
    inputs:
      repo:
        type: string
        default: mentalsmash/uno
      tag-default:
        type: string
        required: true
      tag-static:
        type: string
        required: true
      base-image-default:
        type: string
        required: true
      base-image-static:
        type: string
        required: true
      middleware-default:
        required: true
        type: string
      middleware-static:
        required: true
        type: string


jobs:
  default_image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone uno
        uses: actions/checkout@v4
        with:
          path: src/uno

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone support files
        uses: actions/checkout@v4
        with:
          repository: mentalsmash/uno-ci-arm
          token: ${{ secrets.UNO_CI_ARM_PAT }}
          ref: master
          path: src/uno-ci-arm

      - name: Configure arm64 build
        run: |
          cp src/uno-ci-arm/resource/rti/rti.connext-7.1.0-cp310-cp310-linux_aarch64.whl src/uno

      - name: Build and push default image
        uses: docker/build-push-action@v5
        with:
          file: src/uno/docker/Dockerfile
          tags: ${{ inputs.repo }}:${{ inputs.tag-default }}
          push: true
          context: src/uno
          platforms: linux/amd64,linux/arm64
          build-args: |
            UNO_MIDDLEWARE=${{ inputs.middleware-default }}
            BASE_IMAGE=${{ inputs.base-image-default }}


  static_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push static image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          tags: ${{ inputs.repo }}:${{ inputs.tag-static }}
          push: true
          context: .
          build-args: |
            UNO_MIDDLEWARE=${{ inputs.middleware-static }}
            BASE_IMAGE=${{ inputs.base-image-static }}

